eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
microservice:
  payment-service:
    endpoints:
      endpoint:
        url: http://PAYMENT-MICROSERVICE/paymment/doPayment
    order-service:
      endpoints:
        endpoint:
          url: http://ORDER-MICROSERVICE/order/bookOrder
